title: Freezer magazine
email: rokmabox@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This was Freezer magazine. A free-press project that had some impact on the italian scene.
keywords: fun, info, free-press, italian, surfing, skateboarding, snowboarding, rokma

baseurl: ""
url: "https://freezer.junglestar.org"

github_username:  toybreaker
twitter_creator: rokmatwit
google:
  analytics: UA-57976777-1

# Build settings
markdown: kramdown
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
 - html-proofer
exclude:
  - Gemfile.lock
permalink: pretty


collections:
  articles:
   output: true
   permalink: /projects/:path/
